### INDEX
GET http://localhost:3000/actors.json

###
GET http://localhost:3000/movies.json

### CREATE
POST http://localhost:3000/actors.json
content-type: application/json

{
  "first_name": "Johnny",
  "last_name": "Depp",
  "known_for": "Nightmare on Elm Street",
  "gender": "presumably male",
  "age": 54
}

###
POST http://localhost:3000/movies.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgyNDk2MjZ9.9BKNYumcm6O8v34bVWp1ATladK33iHDkLiwBTdkTENE
content-type: application/json

{
  "title": "Spirited Away",
  "year": 1871,
  "director": "Hayao Miyazaki",
  "plot": "some things happen and then other things happen"
}

### READ
GET http://localhost:3000/actors/13.json

###
GET http://localhost:3000/movies/7.json

### UPDATE
PATCH http://localhost:3000/actors/8.json
content-type: application/json

{
  "first_name": "Wesley",
  "last_name": "Snipes",
  "known_for": "Blade Trilogy",
  "age": 61
}

###
PATCH http://localhost:3000/movies/9.json
content-type: application/json

{
  "plot": "10-year-old Chihiro (Rumi Hiiragi) and her parents (Takashi Naitô, Yasuko Sawaguchi) stumble upon a seemingly abandoned amusement park. After her mother and father are turned into giant pigs, Chihiro meets the mysterious Haku (Miyu Irino), who explains that the park is a resort for supernatural beings who need a break from their time spent in the earthly realm, and that she must work there to free herself and her parents.",
  "year": 2002
}

###
DELETE http://localhost:3000/actors/15

###
DELETE http://localhost:3000/movies/15

### Users Create
POST http://localhost:3000/users
content-type: application/json

{
  "name": "bradford",
  "email": "bradford@email.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions Create
POST http://localhost:3000/sessions
content-type: application/json

{
  "email": "evan@email.com",
  "password": "password"
}
