GET http://localhost:3000/actors/7

###
GET http://localhost:3000/movies/4

###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movie-by-year?compare=before&year=2022

###
GET http://localhost:3000/movie-by-year?year=1988